name: 'Assert'
description:
  'Assert your Github action variables to make sure they are correct.'
author: 'Payadel'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  color: 'green'

# Define your inputs here.
inputs:
  inputs:
    description: 'Inputs with yaml structure'
    required: true
  fail-fast:
    default: 'false'
    required: false
    description: 'Fail with the first error or not?'
  verbose:
    default: 'false'
    required: false
    description:
      'If it is false, only errors will be displayed, otherwise all messages
      will be displayed.'

# Define your outputs here.
outputs:
  success:
    description: 'Are all asserts true or not? (boolean)'
  messagesStr:
    description:
      'Messages include errors and success messages with string type.'
  messages:
    description:
      'Messages with object format include type of message (success or error)
      and message'

runs:
  using: node20
  main: dist/index.js
