name: Continuous Integration

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./
        id: asserts
        continue-on-error: true
        with:
          fail-fast: false
          verbose: true
          inputs: |
            - name: test equals ok
              type: 'Equals'
              expected: '1'
              actual: '1'

            - name: test not equals ok
              type: 'Not-Equals'
              expected: '1'
              actual: '2'

            - name: test true ok
              type: 'True'
              input: 'true'

            - name: test false ok
              type: 'False'
              input: 'false'

            - name: test In ok
              type: 'In'
              member: 'a sample '
              container: 'This is a sample message'

            - name: test Not In ok
              type: 'Not-In'
              member: 'not in text'
              container: 'This is a sample message'

            - name: test greater ok
              type: 'Greater'
              target: 5
              greater_than: 0

            - name: test greater equal ok
              type: 'Greater-Equal'
              target: 5
              greater_equal: 5

            - name: test less ok
              type: 'Less'
              target: 5
              less_than: 10

            - name: test less equal ok
              type: 'Less-Equal'
              target: 5
              less_equal: 5

            - name: test regex ok
              type: 'Regex'
              regex: '[a-zA-Z0-9]+'
              text: 'aB3'
